#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';
use Symfony\Component\Console\Application;
use CityPantry\CityPantryCommand;

$app = new Application();
$app->add(new CityPantryCommand());
$app -> run();
